name: Test Action

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - master
      # - release
      # - production

jobs:
  test:
    runs-on: ubuntu-latest
    name: test changes
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          npm install
      - name: Create commitlint.config.js
        run: |
          echo "module.exports = {extends: ['@commitlint/config-conventional']}" > commitlint.config.js
      - name: Validate commits
        run: |
          npx commitlint --from ${{ github.event.pull_request.base.sha }} --verbose
